server:
  port: 8080
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
      
